server:
  port: 8022
  max-http-header-size: 20480
  servlet:
    context-path: /douyin #request prefix

spring:
  application:
    name: service-feed
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.134.208.93:3306/db_douyin?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#    type: com.alibaba.druid.pool.DruidDataSource
    username: ENC(5Ev24JNagGONP1Ca9+xZWg==)
    password: ENC(lQ3mg76A7j6WOm/j8zQ5dyfaDa06L4FX)

  redis:
    host: 8.134.208.93
    port: 6379
    password: ENC(lQ3mg76A7j6WOm/j8zQ5dyfaDa06L4FX)
    database: 0

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
        loggerLevel: FULL

mybatis:
#  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 令牌桶限流配置
tokenbucket:
  capacity: 100
  rate: 1


jasypt:
  encryptor:
    password: ${DouyinSecretKey}  #解密密钥，通过环境变量读取
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

tencentyun:
  oss:
    cosRegion: ap-guangzhou #地域名
    bucket: douyin-1313537069 # 存储桶名
    secretId: ENC(Z3G9H2hwpdQMR1XbLcQxRr4T0wT8tVfBcUEhhP3PbBU41ODHLXu2hJ/y/95nKkrZ)
    secretKey: ENC(NAVTBxcwmDTcgKidk60YDWNh3t/OiaiuHJLVEshs+R8cFRsy1wFeRwBQ6LVEZ4rZ)
